title: Fotky pomáhají
email: fotkypomahaji@gmail.com
description: >-
  Projekt oceňovaných profesionálních zpravodajských fotografů, kteří se svou prací rozhodli podpořit sbírky na podporu Ukrajiny.
baseurl: ""
url: "https://fotkypomahaji.cz"

theme: minima
minima:
  skin: dark
  social_links:
    github: kubicek/fotkypomahaji
header_pages: 
- o-projektu.md

plugins:
  - jekyll-datapage-generator

imagesurl: "/images/"
thumbsurl: "/thumbs/"

page_gen:
- data: photogs
  template: photographers
  dir: fotografove
  name: slug
  title: name
- data: photos
  dir: fotky
  name: filename
  title: filename

exclude:
  - originals/
